<span style='color:#A24633'> Using Numpy to perfrom arithmetic operations </span>

In [2]:
import numpy as np

In [3]:
np.set_printoptions(precision=2)

In [19]:
aa=np.array([[1.,2.,3.],[4.,5.,6.]])

In [20]:
bb=np.array([[10.,11.],[20.,21.],[30.,31.]])

In [21]:
np.multiply(aa,bb)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [11]:
aa

array([[1, 3],
       [2, 4]])

In [12]:
bb

array([[5, 8],
       [7, 9]])

In [22]:
np.dot(aa,bb)

array([[140., 146.],
       [320., 335.]])

In [14]:
np.dot(np.array([1,2,7]),np.array([3,8,9]))

82